steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/resume-image'
      - '--build-arg'
      - 'CONTENT_PATH=/usr/share/nginx/html/index.html'
      - '--build-arg'
      - 'CONTENT_VALUE=resume.html'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/resume-image']

  # Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'resume-image'
      - '--image'
      - 'gcr.io/$PROJECT_ID/resume-image'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '80'
      - '--allow-unauthenticated'
options:
    logging: CLOUD_LOGGING_ONLY
